# **Part 4**

### Performance comparison between numpy array and dask array: set a timer to calculate the time of the following operations:

### In numpy array, draw random samples from a normal (Gaussian) distribution, the mean of the distribution is 10, the standard deviation of the distribution is 0.1, and the output shape is 20000x20000. Then take the "mean" of x along axis=0 with a step of 100.                                              (10 pts)

### In dask array, do the same thing as above. (Tips: you can set the size of “chunks” to 1000x1000) (10 pts)

### Note: finish the part 4 in one Jupyter file.

In [11]:
# IMPORTING NECESSARY LIBRARIES
import numpy as np

In [12]:
# given arguments
mu = 10                       # mean
sigma = 0.1                   # standard deviation

In [13]:
# drawing random samples in a numpy array
output_nparray = np.random.default_rng().normal(mu, sigma, size=(20000,20000))
output_nparray

distributed.worker - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged memory: 3.93 GiB -- Worker memory limit: 5.59 GiB
distributed.worker - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged memory: 4.03 GiB -- Worker memory limit: 5.59 GiB
distributed.worker - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged memory: 4.12 GiB -- Worker memory limit: 5.59 GiB
distributed.worker - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see 

array([[ 9.84573887, 10.00822206,  9.99442404, ..., 10.0397929 ,
        10.11053897,  9.69527744],
       [10.0046709 , 10.07772575,  9.74732021, ...,  9.93462162,
         9.93385711,  9.97454425],
       [10.07275513,  9.79434847,  9.89893994, ...,  9.9924594 ,
        10.07067302, 10.04573265],
       ...,
       [ 9.88194783,  9.96858747,  9.91094249, ..., 10.08154807,
        10.02606622, 10.02213599],
       [ 9.87660391,  9.97870811, 10.03240462, ..., 10.02662447,
        10.10573206, 10.05910372],
       [ 9.98270273, 10.06750775,  9.94797025, ..., 10.16722229,
        10.07891462,  9.91502916]])

In [14]:
#Setting timer to calculate operation
y= output_nparray
%time time_nparray = y[::100,:].mean(axis=0)
time_nparray

Wall time: 16.4 ms


array([10.00591625, 10.01307855,  9.98800554, ..., 10.01139151,
       10.00520754,  9.99803137])

In [15]:
# Start Dask Client for Dashboard
from dask.distributed import Client, progress
client = Client(processes=False, threads_per_worker=4,
                n_workers=1, memory_limit='6GB')
client

C:\Users\nikit\anaconda3\lib\site-packages\distributed\node.py:160: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 56724 instead
  warnings.warn(


<Client: 'inproc://10.110.113.227/15528/10' processes=1 threads=4, memory=5.59 GiB>

In [16]:
import dask.array as da
x = da.from_array(output_nparray, chunks=(1000,1000))

In [17]:
y= x 
z=y[::100,:].mean(axis=0)
z

dask.array<mean_agg-aggregate, shape=(20000,), dtype=float64, chunksize=(1000,), chunktype=numpy.ndarray>

In [18]:
z.compute()

array([10.00591625, 10.01307855,  9.98800554, ..., 10.01139151,
       10.00520754,  9.99803137])

In [19]:
%time z.compute()

Wall time: 830 ms


array([10.00591625, 10.01307855,  9.98800554, ..., 10.01139151,
       10.00520754,  9.99803137])